
branch-defaults:
  circleCI:
    environment: null
    group_suffix: null
environment-defaults:
  unique-inventory-test:
    branch: null
    repository: null
global:
  application_name: unique-inventory
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application